zenoss/inspector

makefile, scripts/docker-config.sh, scripts/docker-info.sh, scripts/docker-service.sh, scripts/docker-storage.sh
=> Enhance docker inspection

scripts/serviced-config.sh, scripts/serviced-storage.py
=> Collect serviced configuration and validate the storage

scripts/docker-version.sh, scripts/storage-config.sh
=> Collect information about the host's storage configuration

scripts/docker-storage.sh, scripts/service-status.py, scripts/systemctl-status.sh
=> Verify the state of system services for CC

scripts/docker-config.sh, scripts/docker-container-logs.py, scripts/docker-images.sh, scripts/docker-info.sh, scripts/docker-service.sh, scripts/docker-version.sh, scripts/journalctl-docker.sh, scripts/service-status.py, scripts/systemctl-status.sh
Fixes [CC-1846](https://jira.zenoss.com/browse/CC-1846?filter=-1).
=> Fix docker-service.sh to use the correct path 

scripts/selinux-config.sh, scripts/selinux-status.sh
Fixes [CC-1785](https://jira.zenoss.com/browse/CC-1785)
=> Add checks for SELINUX

scripts/hostname.sh
Fixes [CC-1947](https://jira.zenoss.com/browse/CC-1947)
=> add host IP and ID to output from hostname.sh

scripts/free.sh
Only the version was being printed.
=> remove version flag from free

scripts/docker-stats.sh
```sh
$ docker ps -q | xargs docker stats --no-stream
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O
137ff783c7d0        1.32%               240.2 MB / 67.48 GB   0.36%               9.372 kB / 1.639 kB   0 B / 0 B
2cac7e2992b5        6.54%               274.1 MB / 67.48 GB   0.41%               281.6 kB / 276.9 kB   0 B / 622.6 kB
3d78b1c627bc        231.70%             520.1 MB / 67.48 GB   0.77%               4.621 kB / 1.326 kB   0 B / 0 B
4c15eea25245        0.10%               20.09 MB / 67.48 GB   0.03%               8.52 kB / 648 B       0 B / 0 B
5a37b139d01f        20.22%              130.5 MB / 67.48 GB   0.19%               96.57 MB / 360.4 kB   0 B / 0 B
831ee8b878a7        212.42%             1.181 GB / 67.48 …
```
=> docker stats

scripts/kernel-version-check.py
Adds functionality requested in INSP-14
=> Adding kernel version check to ensure fstrim will work

scripts/serviced-config-agent.sh
Specifically, those settings can be:
* 0/1
* true/false
* t/f
* y/n
Finishes INSP-1
=> Support all values for SERVICED_MASTER and SERVICED_AGENT

scripts/check-docker-config.sh
Implements [INSP-34](https://jira.zenoss.com/browse/INSP-34)
=> Verify the --storage-opt parameter in /etc/sysconfig/docker.

scripts/check-ha-config.sh, scripts/docker-version.sh, scripts/drbdadm-dump.sh, scripts/etc-default-serviced-filtered.sh, scripts/etc-default-serviced.sh, scripts/get-drbd-config.sh, scripts/get-drbd-logs.sh, scripts/get-ha-config.sh, scripts/get-ha-versions.sh, scripts/get-kernel-logs.sh, scripts/get-ocf-logs.sh, scripts/get-pacemaker-logs.sh, scripts/get-rpms.sh, scripts/service-status.py, scripts/systemctl-status.sh
=> Additions to collect and check HA info

scripts/check-docker-service.py
=> Removed check for `TasksMax`.

scripts/get-rpms.sh, scripts/lsb-release-a.sh, scripts/lsof.sh
=> Log a warning and exit w/0 if lsb-release or lsof are not installed

scripts/lvs.sh, scripts/pvs.sh, scripts/storage-config.sh, scripts/vgs.sh
=> Capture output from lvs, vgs and pvs

scripts/check-lvmonitor.sh
Fixes INSP-15
DO NOT MEGE UNTIL #60 HAS BEEN MERGED
=> Check for monitoring on serviced-pool

scripts/check-resourceagent.sh
=> Add check for out-of-date resource agents

scripts/check-ha-config.sh, scripts/check-resourceagent.sh
=> Don't complain about serviced-resource-agents if PCS not installed

scripts/service-status.py
Fixes INSP-52
See ticket for details
=> Soften warnings for ntpd

scripts/docker-running.sh
Tested on CC 1.2 on docker 1.12.1:
docker-running.sh                   done
=> INSP-73: Fix check for docker running

scripts/opentsdb-ttl.py, scripts/service-startup-check.py, scripts/serviced-running.sh, scripts/serviced-service-deployed.sh
Skip service-specific checks if CC is not running or no services deployed.
Fixes INSP-74
=> Improve UX when CC not running or no services avail

scripts/check-orphans.sh, scripts/get-orphans.sh
Fixes INSP-82.
See Jira ticket for details on the various test scenarios
=> Add checks for orphaned devices in the CC thinpool

scripts/check-time-drift.py, scripts/time-drift.sh
Created check-time-drift to validate the output of the time difference
=> Created time-drift.sh to check the time difference between systems

scripts/yum-log.sh
=> Collect all yum logs

scripts/nfs-mounts-check.py, scripts/nfs-mounts.sh
Added check for NFS mount version
=> Adding check for bad NFS mount version
